### ISSUE TITLE
[Feature]: Add createdAt and updatedAt to Price and PriceNotification

### ISSUE THREAD

**Issue by mw10013** [PaddleHQ/paddle-node-sdk#13]
### Tell us about your feature request

Add `createdAt` and `updatedAt` to `Price` and `PriceNotification` to align with align with API and webhooks documentation.

### What problem are you looking to solve?

Synchronize and reconcile application database with Paddle.

### How important is this suggestion to you?

Important

**Comment by vijayasingam-paddle** [comment]
Hello @mw10013,
Similar to issue #12, we are aware of this difference in Price entity as well. 
They are both stuck at the same stage and we will be updating them soon.

Thank you.
