### ISSUE TITLE
[Feature]: Expose hasMore and add estimatedTotal to Collection

### ISSUE THREAD

**Issue by mw10013** [PaddleHQ/paddle-node-sdk#14]
### Tell us about your feature request

Expose `hasMore` and add `estimatedTotal` to `Collection` to align with pagination (https://developer.paddle.com/api-reference/about/pagination).

https://github.com/PaddleHQ/paddle-node-sdk/blob/2fb1bb5b09cfcee2c902081cb444d5acd166b45d/src/internal/base/collection.ts#L5-L8

### What problem are you looking to solve?

Facilitate pagination in application.

### How important is this suggestion to you?

Nice to have

**Comment by vijayasingam-paddle** [comment]
Hi @mw10013,
Thank you for your feedback. 

We made a conscious design decision to abstract the internal workings of pagination and not to expose them for general usage. 

With that said, I agree that there could be some benefits of exposing these properties. We will come up with a scalable solution that follows our design philosophy and makes it easy to use.
