### ISSUE TITLE
[Feature]: Provide way to delete all sandbox data

### ISSUE THREAD

**Issue by mw10013** [PaddleHQ/paddle-node-sdk#27]
### Tell us about your feature request

Provide a way to delete all sandbox data.

### What problem are you looking to solve?

- Getting back to a clean slate with a sandbox that has accumulated many exploratory and experimental objects.
- Not having to use fake emails after running out of real emails developing and testing new customer notifications.

### How important is this suggestion to you?

Important

**Comment by vijayasingam-paddle** [comment]
Hi @mw10013, 

Thank you for the feedback. 
We will explore options to introduce this new feature to our sandbox environment in future iterations of our product.

I am going to close this issue as it is not strictly related to SDK. When we implement this feature, it will be added to our vendor dashboard. 

Please let us know if we can help you with anything related to paddle billing, or email `sellers@paddle.com` for any general queries. 

Thank you.
