### ISSUE TITLE
[Bug]: The punycode module is deprecated

### ISSUE THREAD

**Issue by DataGridXL** [PaddleHQ/paddle-node-sdk#31]
### What happened?

[Paddle] [LOG] [Request] GET https://api.paddle.com/products Transaction ID: XXX
(node:4292) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Paddle] [LOG] [Response] GET https://api.paddle.com/products 200 Transaction ID: XXX Request ID: XXX

### Steps to reproduce

Follow the steps from this very Github repo (getProducts) and it will raise this warning.

It seems that it is not a bug (yet) but a warning.

### What did you expect to happen?

I would like to have a clear console without deprecation warning.

**Comment by vijayasingam-paddle** [comment]
Hi @DataGridXL,
Thank you for raising this bug report. 

This is a deprecation warning thrown by one of our dependencies `node-fetch`. We will find a solution to remove them and update you.

Thank you.

**Comment by lukeed** [comment]
This can be closed w/ 2.0 since node-fetch has been removed
