### ISSUE TITLE
[Feature]: Subscription Plan Changed Webhook

### ISSUE THREAD

**Issue by ChampagneChugger** [PaddleHQ/paddle-node-sdk#40]
### Tell us about your feature request

It would be nice to have a special "subscription.plan_changed" webhook. I feel like there is no way to differentiate from "subscription.updated" caused by, for example, pausing the subscription and the "subscription.updated" caused by changing the subscription plan.

### What problem are you looking to solve?

Nearly every subscription change triggers the "subscription.updated" event which can come before or after the main event. For example, I'm trying to implement "subscription plan change" feature, but the only available event that triggers is "subscription.updated". There is no way to differentiate between "subscription.updated" event triggered by pausing the subscription and "subscription.updated" event triggered by changing the subscription plan.

This isn't an issue for anything besides changing the subscription plan, which only triggers "subscription.updated".

### How important is this suggestion to you?

Important

**Comment by vijayasingam-paddle** [comment]
Hi @ChampagneChugger,

Thank you for your feedback. I will pass this along to our product team for assessment. 

Meanwhile, you can compare the price id(`data.items[].price.id`) in the event with the value you have already stored against the subscription in your database to identify if the product (a.k.a plan) has changed in the subscription. 

Please let us know if we can help you with anything else. 

Thank you.

**Comment by ChampagneChugger** [comment]
You are correct, i forgot that i can just check the price id. Thank you for your reply.
