### ISSUE TITLE
[Feature]: Support creating Customer Portal Session

### ISSUE THREAD

**Issue by opswiz** [PaddleHQ/paddle-node-sdk#73]
### Tell us about your feature request

https://developer.paddle.com/api-reference/customer-portals/create-customer-portal-session

Option to create portal session via SDK

### What problem are you looking to solve?

Missing api needs to be added I guess. Rather than using sdk  for half and direct api hits for rest.

### How important is this suggestion to you?

Nice to have

**Comment by danbillson** [comment]
Hey @opswiz, thanks for raising this, we'll look at adding this functionality in the near future, I'll let you know once it is released

**Comment by danbillson** [comment]
@opswiz this feature has now been released in `2.1.0`

https://github.com/PaddleHQ/paddle-node-sdk/pull/74

**Comment by opswiz** [comment]
That was fast. Thanks @danbillson 🚀
